language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=dev

matrix:
  allow_failures:
    - env: DJANGO_VERSION=dev
    - python: "3.3"
    - python: "3.4"
  exclude:
    - env: DJANGO_VERSION=dev
      python: "2.6"
    - env: DJANGO_VERSION=1.7
      python: "2.6"

install:
    - pip install tox

script:
    - tox -e py${TRAVIS_PYTHON_VERSION/./}-${DJANGO_VERSION}
