env:
  - DJANGO=1.3
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
install:
  - pip install PIL django==${DJANGO}
  - pip install .
language: python
python:
  - "2.6"
  - "2.7"
script: python test_project/manage.py test badges_tests
